apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  labels:
    io.kompose.service: ocserv
  name: ocserv
spec:
  ports:
  - name: "443"
    port: 443
    targetPort: 443
  - name: 443-udp
    port: 443
    protocol: UDP
    targetPort: 443
  selector:
    io.kompose.service: ocserv